server:
  port: 8001
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_demo?useSSL=false
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 193.112.58.253
  zipkin:
    base-url: http://193.112.58.253:9005
    sender:
      type: rabbit
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://kang:12345@localhost:9000/eureka/
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
