server:
  port: 9001

spring:
  application:
    name: eureka-node1
  security:
    user:
      password: 12345
      name: kang


eureka:
  client:
    serviceUrl:
      defaultZone: http://kang:12345@localhost:9001/eureka/,http://kang:12345@localhost:9002/eureka/
  instance:
    hostname: localhost
  server:  #配置属性，但由于 Eureka 自我保护模式以及心跳周期长的原因，经常会遇到 Eureka Server 不剔除已关停的节点的问题
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000